### PR TITLE
Fonts after ufo2ft fix

### PR DESCRIPTION
**Pull request by vv-monsalve**
Hi @arturschmal,

This PR includes:

- [x] Inclusion of ufo2ft in the requirements.txt file
- [x] Version number increased to 1.301 to register the improvements
- [x] New fonts produced

I think we could be ready to go onboard. Nevertheless, please inspect the Diffenator Reports for both [Roman](https://github.com/originaltype/kufam/issues/22) and [Italic](https://github.com/originaltype/kufam/issues/16) and the complete reports in the Diffenator folder attached [here](https://github.com/originaltype/kufam/issues/16#issuecomment-772096767).

After the merge, please include the instructions for adding the Arabic from Roman to the Italic source if there are future inclusions or modifications to it.

### CODE REVIEW

**Comment by arturschmal** [comment]
Hi @vv-monsalve,

I've merged this pull request. All issues concerning the Latin are resolved as far as I can see. There are however still issues with the Arabic and @waelmorcos is currently working to solve these issues. I need to manually merge his changes into the source file, so there will at least be one new build of the fonts.

@waelmorcos writes to me concerning the marks:

> The issue with Variable fonts and anchors/vocalization marks is an issue with all the Google Fonts Arabic variable fonts. Basically the forms gets thicker but don’t around so they overlap when the font gets thicker. Not sure how it’s done for Latin letters with accents, perhaps the simplicity of Latin letters doesn’t cause overlap issues?

**Comment by vv-monsalve** [comment]
> The issue with Variable fonts and anchors/vocalization marks is an issue with all the Google Fonts Arabic variable fonts. Basically the forms gets thicker but don’t around so they overlap when the font gets thicker. Not sure how it’s done for Latin letters with accents, perhaps the simplicity of Latin letters doesn’t cause overlap issues?

I haven't seen that for the Latin fonts. They go thicker according to the paths in the source file, that is the coordinates of the nodes, with no overlapping issue unless it's coming from the file. 

Have you inspected if there is an open issue on that? Otherwise, please file one.

**Comment by simoncozens** [comment]
[An example](https://fonts.google.com/specimen/Markazi+Text?subset=arabic&preview.text=نّ&preview.text_type=custom) of the Arabic problem, looks like mkmk are not being interpolated. (Another example with [Kufam](https://fonts.google.com/specimen/Kufam?subset=arabic&vfonly=true&preview.text=نَ&preview.text_type=custom#standard-styles))

**Comment by simoncozens** [comment]
Actually the variable font is fine in FontGoggles, but the web preview on fonts.google.com is broken.

**Comment by simoncozens** [comment]
And maybe it's not even the WOFF file, just weirdness with the web previewer. Click on the specimen text and it fixes itself:
Kufam

**Comment by simoncozens** [comment]
Reported with Google Fonts as https://github.com/google/fonts/issues/2994

**Pull request merged**
